name: Release Build

on:
  push:
    branches:
      - release

jobs:
  deploy:
    uses: InTouchSO/cards-ci/.github/workflows/card-release.yml@stable
    secrets:
      WEBAPP_DEPLOY_TOKEN: ${{ secrets.WEBAPP_DEPLOY_TOKEN }}
